export enum TipoNotificacao {
  AGENDAMENTO_SOLICITADO = 'AGENDAMENTO_SOLICITADO',
  AGENDAMENTO_ACEITO = 'AGENDAMENTO_ACEITO',
  AGENDAMENTO_REJEITADO = 'AGENDAMENTO_REJEITADO',
  AGENDAMENTO_CANCELADO = 'AGENDAMENTO_CANCELADO',
  AGENDAMENTO_RECUSADO = 'AGENDAMENTO_RECUSADO'
}

export enum StatusNotificacao {
  NAO_LIDA = 'NAO_LIDA',
  LIDA = 'LIDA',
}